name: Test Hugo Build

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Hugo
      run: |
        HUGO_VERSION="0.37.1"
        HUGO_PACKAGE="hugo_${HUGO_VERSION}_Linux-64bit.tar.gz"
        wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_PACKAGE}"
        tar -xzvf ${HUGO_PACKAGE}
        sudo mv hugo /usr/local/bin/
        hugo version  # Verify Hugo installation

    - name: Build Hugo Site
      run: hugo --verbose
