name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - master  # Change this to your main branch if different, e.g., main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Hugo
      run: |
        set -x  # Enable debug mode
        HUGO_VERSION="0.37.1"
        HUGO_PACKAGE="hugo_${HUGO_VERSION}_Linux-64bit.tar.gz"
        wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_PACKAGE}"
        tar -xzvf ${HUGO_PACKAGE}
        sudo mv hugo /usr/local/bin/
        hugo version  # Verify Hugo installation

    - name: Verify Directory and File Permissions
      run: |
        echo "Listing root directory:"
        ls -alh
        echo "Listing project directory:"
        ls -alh $GITHUB_WORKSPACE
        echo "Listing public directory if it exists:"
        ls -alh $GITHUB_WORKSPACE/public || true

    - name: Build Hugo Site
      run: |
        set -x  # Enable debug mode
        hugo --verbose

    - name: List Generated Files
      run: |
        echo "Listing files in public directory:"
        ls -R public
